name: CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "modernize-phase-1" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Build Jekyll
        run: bundle exec jekyll build
      - name: HTMLProofer
        run: bundle exec htmlproofer ./_site --config .htmlproofer.yml
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: Run Lighthouse CI
        run: lhci autorun
